"""ARCANA AI — Live Code Integrator.

Hot-reloads API wrappers generated by APIEvolver into live ARCANA operations
without requiring a restart. Also manages the integration registry and
routes API capabilities to the right ARCANA subsystems.

The flow:
1. APIEvolver generates a wrapper → saves to src/integrations/<name>.py
2. LiveIntegrator detects new module → imports it dynamically
3. Routes the new capability to relevant ARCANA subsystem
4. Tests the integration with a health check
5. Registers it for monitoring

This is how ARCANA grows new capabilities at runtime.
"""

from __future__ import annotations

import importlib
import importlib.util
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.llm import LLM, Tier
from src.memory import Memory

logger = logging.getLogger("arcana.live_integrator")

# Maps API categories to ARCANA subsystems they can enhance
CAPABILITY_ROUTING = {
    "lead_generation": ["scanner", "outreach", "crm"],
    "content_creation": ["content_engine", "seo", "ugc", "newsletter"],
    "payment_processing": ["payments", "fulfillment"],
    "communication": ["email", "notify", "discord"],
    "analytics": ["analytics", "evolution_tracker", "revenue"],
    "automation": ["scheduler", "skill_executor", "fulfillment"],
    "ai_ml": ["llm", "content_engine", "scanner"],
}


class IntegrationRecord:
    """Track a live integration."""

    def __init__(
        self, module_name: str, class_name: str,
        category: str, api_name: str,
    ) -> None:
        self.module_name = module_name
        self.class_name = class_name
        self.category = category
        self.api_name = api_name
        self.status = "loaded"  # loaded, active, failed, disabled
        self.loaded_at = datetime.now(timezone.utc).isoformat()
        self.last_used = ""
        self.call_count = 0
        self.error_count = 0
        self.instance: Any = None  # Live instance of the client

    def to_dict(self) -> dict[str, Any]:
        return {
            "module_name": self.module_name,
            "class_name": self.class_name,
            "category": self.category,
            "api_name": self.api_name,
            "status": self.status,
            "loaded_at": self.loaded_at,
            "last_used": self.last_used,
            "call_count": self.call_count,
            "error_count": self.error_count,
        }


class LiveIntegrator:
    """Dynamically loads and manages API integrations at runtime."""

    def __init__(self, llm: LLM, memory: Memory) -> None:
        self.llm = llm
        self.memory = memory
        self.integrations_dir = Path("src/integrations")
        self._registry: dict[str, IntegrationRecord] = {}
        self._load_registry()

    def _load_registry(self) -> None:
        """Load integration registry from memory."""
        data = self.memory.get_tacit("live-integrations")
        if not data:
            return
        try:
            json_start = data.find("{")
            if json_start >= 0:
                parsed = json.loads(data[json_start:])
                for name, rec_data in parsed.items():
                    rec = IntegrationRecord(
                        rec_data["module_name"],
                        rec_data["class_name"],
                        rec_data.get("category", ""),
                        rec_data.get("api_name", name),
                    )
                    rec.status = rec_data.get("status", "loaded")
                    rec.loaded_at = rec_data.get("loaded_at", "")
                    rec.call_count = rec_data.get("call_count", 0)
                    rec.error_count = rec_data.get("error_count", 0)
                    self._registry[name] = rec
        except (json.JSONDecodeError, KeyError, TypeError):
            pass

    def _save_registry(self) -> None:
        """Persist registry."""
        data = {name: rec.to_dict() for name, rec in self._registry.items()}
        self.memory.save_tacit("live-integrations", json.dumps(data, indent=2))

    def scan_for_new_modules(self) -> list[str]:
        """Scan src/integrations/ for new, unloaded modules."""
        new_modules = []
        if not self.integrations_dir.exists():
            return new_modules

        for path in self.integrations_dir.glob("*.py"):
            if path.name.startswith("_"):
                continue
            module_name = f"src.integrations.{path.stem}"
            if module_name not in [r.module_name for r in self._registry.values()]:
                new_modules.append(path.stem)

        return new_modules

    def load_module(self, name: str) -> IntegrationRecord | None:
        """Dynamically import a module from src/integrations/."""
        module_path = self.integrations_dir / f"{name}.py"
        if not module_path.exists():
            logger.error("Module not found: %s", module_path)
            return None

        module_name = f"src.integrations.{name}"

        try:
            # Force reload if already imported
            if module_name in sys.modules:
                module = importlib.reload(sys.modules[module_name])
            else:
                spec = importlib.util.spec_from_file_location(module_name, module_path)
                if spec is None or spec.loader is None:
                    return None
                module = importlib.util.module_from_spec(spec)
                sys.modules[module_name] = module
                spec.loader.exec_module(module)

            # Find the main client class (first class that ends with Client or API)
            class_name = None
            client_class = None
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if isinstance(attr, type) and attr_name != "object":
                    if attr_name.endswith(("Client", "API", "Service", "Wrapper")):
                        class_name = attr_name
                        client_class = attr
                        break

            if not class_name:
                # Fallback: find any class defined in this module
                for attr_name in dir(module):
                    attr = getattr(module, attr_name)
                    if isinstance(attr, type) and getattr(attr, "__module__", "") == module_name:
                        class_name = attr_name
                        client_class = attr
                        break

            if not class_name:
                logger.warning("No client class found in %s", name)
                return None

            # Try to instantiate
            try:
                instance = client_class()
            except TypeError:
                # Class needs args — store as None, will be instantiated when needed
                instance = None

            record = IntegrationRecord(
                module_name=module_name,
                class_name=class_name,
                category="",  # Will be determined by categorize_integration
                api_name=name,
            )
            record.instance = instance
            record.status = "loaded"
            self._registry[name] = record
            self._save_registry()

            logger.info("Loaded integration: %s.%s", module_name, class_name)
            return record

        except Exception as exc:
            logger.error("Failed to load module %s: %s", name, exc)
            return None

    async def categorize_integration(self, name: str) -> str:
        """Use LLM to categorize what an integration does."""
        record = self._registry.get(name)
        if not record:
            return ""

        module_path = self.integrations_dir / f"{name}.py"
        code = module_path.read_text()[:1500] if module_path.exists() else ""

        result = await self.llm.ask_json(
            f"Categorize this API integration.\n\n"
            f"Module: {name}\n"
            f"Class: {record.class_name}\n"
            f"Code preview:\n{code}\n\n"
            f"Categories: {list(CAPABILITY_ROUTING.keys())}\n\n"
            f'Return JSON: {{"category": str, "description": str, '
            f'"enhances": [str] (which ARCANA systems this can help)}}',
            tier=Tier.HAIKU,
        )

        category = result.get("category", "automation")
        record.category = category
        self._save_registry()

        return category

    async def hot_reload_all(self) -> dict[str, Any]:
        """Scan for new modules and load them all."""
        new_modules = self.scan_for_new_modules()
        loaded = []
        failed = []

        for name in new_modules:
            record = self.load_module(name)
            if record:
                await self.categorize_integration(name)
                loaded.append(name)
            else:
                failed.append(name)

        if loaded:
            self.memory.log(
                f"Hot-reloaded {len(loaded)} new integrations: {', '.join(loaded)}",
                "Live Integrator",
            )

        return {
            "scanned": len(new_modules),
            "loaded": loaded,
            "failed": failed,
        }

    def get_integration(self, name: str) -> Any | None:
        """Get a live integration instance by name."""
        record = self._registry.get(name)
        if record and record.instance and record.status != "disabled":
            record.call_count += 1
            record.last_used = datetime.now(timezone.utc).isoformat()
            return record.instance
        return None

    def get_integrations_for_category(self, category: str) -> list[IntegrationRecord]:
        """Get all integrations for a capability category."""
        return [
            r for r in self._registry.values()
            if r.category == category and r.status in ("loaded", "active")
        ]

    def record_error(self, name: str) -> None:
        """Record an error for an integration."""
        record = self._registry.get(name)
        if record:
            record.error_count += 1
            if record.error_count > 10 and record.call_count > 0:
                error_rate = record.error_count / record.call_count
                if error_rate > 0.5:
                    record.status = "disabled"
                    logger.warning("Disabled integration %s (error rate: %.1f%%)",
                                   name, error_rate * 100)
            self._save_registry()

    def format_report(self) -> str:
        """Format integration status for reports."""
        active = [r for r in self._registry.values() if r.status in ("loaded", "active")]
        disabled = [r for r in self._registry.values() if r.status == "disabled"]

        lines = [
            f"**Live Integrations**: {len(active)} active, {len(disabled)} disabled",
        ]
        for r in sorted(active, key=lambda x: -x.call_count)[:5]:
            lines.append(
                f"  {r.api_name} ({r.category}): "
                f"{r.call_count} calls, {r.error_count} errors"
            )
        return "\n".join(lines)
